### ISSUE TITLE
Projects and Proposals move to README

### ISSUE THREAD

**Issue by josephworks** [MrClarkeSoftware/CSharpProject#45]
I think we should move the content form the projects and proposal files to the README.

This will also create a conflict with the branches that the users will have to fix. Essential learning experience in my opinion.

**Comment by jtbri484** [comment]
Yes I agree with Joseph.

**Comment by josephworks** [comment]
When I become unlazy, I might do this possibly.

**Comment by josephworks** [comment]
W8 nvm, this is fixed
